### ISSUE TITLE
java.lang.Exception: SyntaxError: Private names are only allowed in property accesses (`obj.#mongo`) or in `in` expressions (`#mongo in obj`). (1:0)

### ISSUE THREAD

**Issue by FangPengbo** [DataGrip/mongo-jdbc-driver#27]
```
> 1 | #mongo 
    | ^
  2 |
  3 | db.getCollection('d0eaf6d6c0baeb08e0d8f080c412c656_59bf52eaeb1a48d3b51c2729fe3b62e6_base').remove({
  4 |  process_instance_id: {
    at Parser._raise (all-standalone.js:734:17451)
    at Parser.raiseWithData (all-standalone.js:734:17390)
    at Parser.raise (all-standalone.js:734:16855)
    at Parser.parseExprOp (all-standalone.js:734:211059)
    at Parser.parseExprOps (all-standalone.js:734:210878)
    at Parser.parseMaybeConditional (all-standalone.js:734:210282)
    at Parser.parseMaybeAssign (all-standalone.js:734:209608)
    at Parser.parseExpressionBase (all-standalone.js:734:208738)
    at all-standalone.js:734:208637
    at Parser.allowInAnd (all-standalone.js:734:241873)
```

**Comment by kornilova203** [comment]
Hi!
I don't understand what is `#mongo` here. How to reproduce it?
